import type { Metadata } from "next";
import { Black_Ops_One, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { BackgroundBeams } from "@/components/ui/beams";


const blackOpsOne = Black_Ops_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-black-ops-one",
});

export const metadata: Metadata = {
  title: "EmilHubb Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        blackOpsOne.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col relative ">
        <BackgroundBeams
          className="pointer-events-none -z-30 bg-black"
        />
        {children}
      </body>
    </html>
  );
}
